services:
  db:
    ports: 
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123"
    user: root
    # mssql server image isn't available for arm64 architecture, so we use azure-sql instead
    image: mcr.microsoft.com/mssql/server:2022-latest
    # If you really want to use MS SQL Server, uncomment the following line
    #image: mcr.microsoft.com/mssql/server
    volumes:
      - ./Facharbeit.SQL/ :/var/opt/mssql/data/
  web:
    build: Facharbeit.Backend/
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/